/********************************************* Disclaimer *********************************************/
/* This file is generated by aiecompiler 2022.1. */
/* Changes to this file may cause incorrect behavior and will be lost if aiecompiler is invoked again.*/

#include <iostream>
#include "adf/adf_api/AIEControlConfig.h"


/************************** Graph Configurations  *****************************/

  adf::GraphConfig GraphConfigurations[] = {
  //{id, name, graphLoadElfFunc, graphInitFunc, graphDebugHalt, coreColumns, coreRows, iterMemColumns, iterMemRows, iterMemAddrs, triggered, plKernelInstanceNames, plAxiLiteModes, plDriverStartFuncs, plDriverCheckIPDoneFuncs}
    {0, "my_graph", nullptr, nullptr, nullptr, {25}, {0}, {24}, {0}, {0x2004}, {0}, {}, {}, {}, {},  }, 
  };
  const int NUM_GRAPH = 1;


/************************** RTP Configurations  *****************************/

  adf::RTPConfig RTPConfigurations[] = {
  //{portId, aliasId, portName, aliasName, graphId, isInput, isAsync, isConnect, elemType, numBytes, isPL, hasLock, selectorColumn, selectorRow, selectorAddr, selectorLockId, pingColumn, pingRow, pingAddr, pongColumn, pongRow, pongAddr, pongLockId, plKernelInstanceName, plParameterIndex, plDriverWriteRTP, plDriverReadRTP}
    {6, 4, "my_graph.k.in[1]", "my_graph.coeffs", 0, true, true, false, (adf::RTPConfig::elementType)2, 32, false, true, 24, 0, 0, 0, 24, 0, 0x6000, 1, 24, 0, 0x4000, 2, "", -1, nullptr, nullptr},
  };
  const int NUM_RTP = 1;

/************************** PLIO Configurations  *****************************/

  adf::PLIOConfig PLIOConfigurations[] = {
  //{id, name, loginal_name, shim_column, slaveOrMaster, streamId}
    {0, "in1", "DataIn1", 25, 0, 0},
    {1, "out1", "DataOut1", 25, 1, 0},
  };
  const int NUM_PLIO = 2;


/************************** ADF API initializer *****************************/

  class InitializeAIEControlXRT
  {
  public:
    InitializeAIEControlXRT()
    {
      std::cout<<"Initializing ADF API..."<<std::endl;
#ifdef __EXCLUDE_PL_CONTROL__
      bool exclude_pl_control = true;
#else
      bool exclude_pl_control = false;
#endif
      adf::initializeConfigurations(nullptr, 0, 0, 0,
                                    GraphConfigurations, NUM_GRAPH,
                                    RTPConfigurations, NUM_RTP,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    nullptr, 0,
                                    PLIOConfigurations, NUM_PLIO,
                                    nullptr, 0, 0, nullptr,
                                    false, exclude_pl_control, false, nullptr,
                                    true, 2);

    }
  } initAIEControlXRT;



#if !defined(__CDO__)

// Kernel Stub Definition
  void filter2D(input_window<short> *,short const (&)[16],output_window<short> *) { /* Stub */ } 
#endif
